services:
  neo4j-kaori:
    image: neo4j:latest
    container_name: neo4j-kaori
    user: root
    build:
      context: .
      dockerfile: docker/neo4j/Dockerfile
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
      - ./backups:/var/lib/neo4j/import
      - ./init.cypher:/var/lib/neo4j/import/init.cypher
    command: >
          bash -c "
          /startup/docker-entrypoint.sh neo4j &
          echo 'Menunggu Neo4j siap...' &&
          until wget --spider -q http://localhost:7474/; do sleep 1; done &&
          echo 'Neo4j siap, mengeksekusi init.cypher...' &&
          cypher-shell -u \${NEO4J_USER} -p \${NEO4J_PASSWORD} -f /var/lib/neo4j/import/init.cypher &&
          echo 'Vector Index berhasil dikonfigurasi!' &&
          wait"
  kaori-app:
    image: kaori:latest
    build: 
     context: .
     dockerfile: docker/fastapi/Dockerfile
    container_name: kaori-app
    ports:
      - "8001:8001"
    environment:
      - NEO4J_URI=bolt://neo4j-kaori:7687
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
    volumes:
      - ./app:/app/app
      - ./backups:/app/backups:ro # read-only
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload